export const CHANGE_SECOND_MAX_FLOW = 'CHANGE_SECOND_MAX_FLOW';
export const CHANGE_DAILY_WATER_FLOW = 'CHANGE_DAILY_WATER_FLOW';
export const IS_OPEN_SCHEME = 'IS_OPEN_SCHEME';
export const IS_VALIDATE_ERROR = 'IS_VALIDATE_ERROR';
export const COUNT_MODE = 'COUNT_MODE';
export const RESULT_MODE = 'RESULT_MODE';
export const DEVICE_DIAGRAM = 'DEVICE_DIAGRAM';
